### ISSUE TITLE
13 Investments

### ISSUE THREAD

**Issue by felmey** [clktmr/gnome-shell-portfolio-manager#2]
Hi, 
I'm trying to add 13 investments to track but eventually the input window runs out of space and there is no way to scroll down to input or view additional items.  As a work around, I tried to find the file in which the investment information is stored to edit it manually, but couldn't.  However, you still wouldn't be able to view beyond the first 8 or 9 entries.

Thanks for a great app!

**Comment by clktmr** [comment]
Thanks for reporting this. The investements are saved in `~/.local/share/gnome-shell-portfolio-manager/config.json`.

**Comment by felmey** [comment]
Thanks!  I was able to edit that file and get my entire portfolio input.  (I use an ETF based portfolio of funds.)  At least I can see the percent change in the top bar, and when I click on it I can see the total numbers.  However, the last few investments do not make it on the display as suspected.  Works well though!

**Comment by clktmr** [comment]
Fixed with commit 1039aa77d63dea1ea719a5cf42d3a64183ea843e
